# Generated by Django 4.1 on 2023-02-23 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('register', '0003_alter_register_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('descript', models.TextField()),
                ('files', models.FileField(upload_to='documents/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.register')),
            ],
        ),
    ]
