# Generated by Django 4.1 on 2023-02-23 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='files',
            field=models.TextField(),
        ),
    ]
